# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  jq: circleci/jq@2.2.0

jobs:
  release:
    working_directory: ~/test/repo
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout

      - jq/install

      - run:
          name: Delete previous release
          command: |
            id=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Switcheo/starport/releases/latest | jq '.id')
            curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/Switcheo/starport/releases/$id
          when: always

      - run:
          name: Delete previous tag
          command: | 
            curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/Switcheo/starport/git/refs/tags/latest
            sleep 2
          when: always

      - run:
          name: Create release with new tag
          command: |
            curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/Switcheo/starport/releases \
            -d '{"tag_name": "latest" }'
          when: always

workflows:
  release:
    jobs:
      - release